# Generated by Django 4.1.7 on 2023-03-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateField(null=True)),
                ('age', models.CharField(max_length=240, null=True)),
                ('gender', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('email', models.CharField(max_length=240, null=True)),
                ('address', models.CharField(max_length=240, null=True)),
                ('District', models.CharField(max_length=240, null=True)),
                ('Branch', models.CharField(max_length=240, null=True)),
                ('account', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=240, null=True)),
                ('meterials', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
