# Generated by Django 4.1.7 on 2023-03-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_data_form_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_form',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
